.mode columns
.header on
.nullvalue NULL

PRAGMA foreign_keys = ON;
CREATE TRIGGER IF NOT EXISTS PRECOCUSTOSADICIONAISVALIDO
BEFORE INSERT ON ORCAMENTOTRANSPORTE
FOR EACH ROW
WHEN (New.TIPOSERVICO = 'normal' and New.CUSTOSADICIONAIS > 20)
BEGIN
    SELECT RAISE(rollback, 'PRECO MAXIMO DOS CUSTOS ADICIONAIS PARA UM SERVICO NORMAL = 20')
END;
END;




