.mode columns
.header on
.nullvalue NULL

PRAGMA foreign_keys = ON;

CREATE TRIGGER IF NOT EXISTS updateStock
BEFORE INSERT ON ENCOMENDA
FOR EACH ROW
    WHEN (NOT EXISTS (SELECT PRODUTOS.QUANTIDADEEMSTOCK FROM PRODUTOS WHERE ((NEW.IDPRODUTOS= PRODUTOS.IDPRODUTOS) AND (PRODUTOS.QUANTIDADEEMSTOCK > 1))))
BEGIN
    SELECT RAISE(ROLLBACK,'O produto não existe em stock');
END;


CREATE TRIGGER IF NOT EXISTS existeStock
AFTER INSERT ON ENCOMENDA
FOR EACH ROW
BEGIN
    UPDATE PRODUTOS SET QUANTIDADEEMSTOCK = QUANTIDADEEMSTOCK - 1 WHERE (PRODUTOS.IDPRODUTOS = NEW.IDPRODUTOS);
END;













